Feature project 1/delete project
flow-rs/flowrs-build pull request #17
Opened 2023-10-29 09:30 UTC by Tobias-Pe

closes #16 

also contains a refactor to give out errors from commands, so users can see why their command failed

2023-10-29 09:31 UTC, Tobias-Pe commented
TODO implement website connection point in api

2023-10-31 12:27 UTC, christianringmayr requested changes

2023-10-31 12:27 UTC, christianringmayr commented on flowrs-build-designer/repository/modules/projects.ts
> +    async deleteProject(project: ProjectIdentifier): Promise<FlowProject> {
Hier muss ein String als Promise rauskommen

2023-11-01 17:22 UTC, mophima commented on flowrs-build-designer/yarn.lock
bitte rausnehmen

2023-11-03 19:30 UTC, merged